use fgf::field::Field;
use fgf::{Gf8B, gf8b};
use poly_ring::Polynomial;
use polymat::PolynomialMatrix;

type E = <Gf8B as Field>::Elem;

fn b(value: u8) -> E {
    gf8b::Elem::from_raw(value)
}

fn poly(coefficients: &[E]) -> Polynomial<Gf8B> {
    Polynomial::from_coefficients(coefficients).unwrap()
}

fn matrix(rows: usize, columns: usize, flat: Vec<Polynomial<Gf8B>>) -> PolynomialMatrix<Gf8B> {
    PolynomialMatrix::from_entries(rows, columns, flat).unwrap()
}

fn mul_matrix(
    left: &PolynomialMatrix<Gf8B>,
    right: &PolynomialMatrix<Gf8B>,
) -> PolynomialMatrix<Gf8B> {
    let (rows, _) = left.shape();
    let (_, columns) = right.shape();
    let mut out = PolynomialMatrix::zeros(rows, columns).unwrap();
    left.mul_into(right, &mut out).unwrap();
    out
}

#[test]
fn rank_counts_nonzero_reduced_rows() {
    let full_rank = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1)]),
            poly(&[b(2)]),
            poly(&[b(3)]),
            poly(&[b(4), b(1)])
        ],
    );
    assert_eq!(full_rank.rank_weak_popov(&[0, 0]).unwrap(), 2);
    let one_plus_x = poly(&[b(1), b(1)]);
    let r0c0 = poly(&[b(1), b(1)]);
    let r0c1 = poly(&[b(1)]);
    let dependent = matrix(
        2,
        2,
        alloc::vec![
            r0c0.clone(),
            r0c1.clone(),
            r0c0.multiply(&one_plus_x).unwrap(),
            r0c1.multiply(&one_plus_x).unwrap(),
        ],
    );
    // Second row is (1+x) times the first; rank over Fq(x) is 1.
    assert_eq!(dependent.rank_weak_popov(&[0, 0]).unwrap(), 1);
    let zero = PolynomialMatrix::<Gf8B>::zeros(2, 2).unwrap();
    assert_eq!(zero.rank_weak_popov(&[0, 0]).unwrap(), 0);
}

#[test]
fn reduced_leading_columns_mark_zero_rows() {
    let mut basis = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1)]),
            Polynomial::zero(),
            Polynomial::zero(),
            poly(&[b(1)])
        ],
    );
    basis.reduce_weak_popov(&[0, 0]).unwrap();
    assert_eq!(
        basis.reduced_leading_columns(&[0, 0]),
        alloc::vec![Some(0), Some(1)]
    );
    let zero = PolynomialMatrix::<Gf8B>::zeros(1, 2).unwrap();
    assert_eq!(zero.reduced_leading_columns(&[0, 0]), alloc::vec![None]);
}

#[test]
fn left_kernel_annihilates_and_covers_rank_nullity() {
    // [[1+x, 1],[1+x^2, 1+x]] has rank 1; kernel is generated by [1+x, 1].
    let basis = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1), b(1)]),
            poly(&[b(1)]),
            poly(&[b(1), b(0), b(1)]),
            poly(&[b(1), b(1)]),
        ],
    );
    let kernel = basis.left_kernel_weak_popov(&[0, 0]).unwrap();
    let (krows, kcolumns) = kernel.shape();
    assert_eq!(kcolumns, 2);
    assert_eq!(krows, 1);
    assert_eq!(basis.rank_weak_popov(&[0, 0]).unwrap() + krows, 2);
    let product = mul_matrix(&kernel, &basis);
    for row in 0..krows {
        for column in 0..2 {
            assert!(product.entry(row, column).unwrap().is_zero());
        }
    }
    // Independent rows have an empty kernel.
    let independent = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1)]),
            Polynomial::zero(),
            Polynomial::zero(),
            poly(&[b(1)])
        ],
    );
    assert_eq!(
        independent.left_kernel_weak_popov(&[0, 0]).unwrap().shape(),
        (0, 2)
    );
    // Zero matrix: kernel is the full identity module.
    let zero = PolynomialMatrix::<Gf8B>::zeros(2, 3).unwrap();
    let kernel = zero.left_kernel_weak_popov(&[0, 0, 0]).unwrap();
    assert_eq!(kernel.shape(), (2, 2));
}

#[test]
fn right_kernel_annihilates_transposed_problem() {
    // Column relation: second column is (1+x) times the first.
    let basis = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1)]),
            poly(&[b(1), b(1)]),
            poly(&[b(2)]),
            poly(&[b(2), b(2)]),
        ],
    );
    let kernel = basis.right_kernel_weak_popov(&[0, 0]).unwrap();
    assert_eq!(kernel.shape().1, 2);
    assert_eq!(kernel.shape().0, 1);
    let product = mul_matrix(&basis, &kernel.transposed().unwrap());
    for row in 0..2 {
        assert!(product.entry(row, 0).unwrap().is_zero());
    }
}

#[test]
fn membership_recovers_witness_and_rejects_nonmembers() {
    let mut basis = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1), b(1)]),
            poly(&[b(1)]),
            poly(&[b(1), b(0), b(1)]),
            poly(&[b(1), b(1)]),
        ],
    );
    basis.reduce_weak_popov(&[0, 0]).unwrap();
    // Target = (1+x) * row0 + x * row1 of the reduced basis.
    let pivot0: Vec<Polynomial<Gf8B>> =
        (0..2).map(|c| basis.entry(0, c).unwrap().clone()).collect();
    let pivot1: Vec<Polynomial<Gf8B>> =
        (0..2).map(|c| basis.entry(1, c).unwrap().clone()).collect();
    let one_plus_x = poly(&[b(1), b(1)]);
    let x = poly(&[b(0), b(1)]);
    let mut target = alloc::vec![Polynomial::zero(), Polynomial::zero()];
    for (column, entry) in target.iter_mut().enumerate() {
        let mut first = pivot0[column].multiply(&one_plus_x).unwrap();
        let second = pivot1[column].multiply(&x).unwrap();
        first.add_assign(&second).unwrap();
        *entry = first;
    }
    let witness = basis.membership_weak_popov(&target, &[0, 0]).unwrap();
    let mut rebuilt = alloc::vec![Polynomial::zero(), Polynomial::zero()];
    for (row, quotient) in witness.quotients.iter().enumerate() {
        for (column, slot) in rebuilt.iter_mut().enumerate() {
            let term = basis
                .entry(row, column)
                .unwrap()
                .multiply(quotient)
                .unwrap();
            slot.add_assign(&term).unwrap();
        }
    }
    assert_eq!(rebuilt, target);
    // A target with a leading column no pivot covers is a non-member.
    let lone = alloc::vec![Polynomial::zero(), poly(&[b(1), b(0), b(0), b(0), b(1)])];
    let reduced_columns = basis.reduced_leading_columns(&[0, 0]);
    let _ = reduced_columns;
    let single = matrix(1, 2, alloc::vec![poly(&[b(1), b(1)]), Polynomial::zero()]);
    let mut single = single;
    single.reduce_weak_popov(&[0, 0]).unwrap();
    assert!(single.membership_weak_popov(&lone, &[0, 0]).is_err());
}

#[test]
fn scalar_solve_handles_unit_nonunit_and_inconsistent() {
    // x * z = x solves with 1.
    let unit = matrix(1, 1, alloc::vec![poly(&[b(0), b(1)])]);
    let solution = unit.solve_weak_popov(&[poly(&[b(0), b(1)])], &[0]).unwrap();
    assert_eq!(solution.particular.len(), 1);
    assert!(
        solution.particular[0]
            .multiply(&poly(&[b(0), b(1)]))
            .unwrap()
            .sub(&poly(&[b(0), b(1)]))
            .unwrap()
            .is_zero()
    );
    // x * z = 1 is inconsistent over Fq[x].
    assert!(unit.solve_weak_popov(&[poly(&[b(1)])], &[0]).is_err());
    // Nonunit common factor: [x] * z = [x^2] solves with [x].
    let solution = unit
        .solve_weak_popov(&[poly(&[b(0), b(0), b(1)])], &[0])
        .unwrap();
    let check = solution.particular[0]
        .multiply(&poly(&[b(0), b(1)]))
        .unwrap();
    assert_eq!(check, poly(&[b(0), b(0), b(1)]));
}

#[test]
fn kernel_combinations_preserve_solutions() {
    let basis = matrix(
        1,
        2,
        alloc::vec![poly(&[b(1), b(1)]), poly(&[b(1), b(0), b(1)])],
    );
    let target = alloc::vec![poly(&[b(1), b(0), b(0), b(0), b(1)])];
    let solution = basis.solve_weak_popov(&target, &[0, 0]).unwrap();
    // Verify A * particular == target via the transpose identity.
    let particular_matrix =
        PolynomialMatrix::from_entries(2, 1, solution.particular.clone()).unwrap();
    let check = mul_matrix(&basis, &particular_matrix);
    assert_eq!(check.entry(0, 0).unwrap(), &target[0]);
    // Kernel rows annihilate: A * (particular + N^T w) == target for any w.
    let (krows, _) = solution.kernel.shape();
    for row in 0..krows {
        let generator: Vec<Polynomial<Gf8B>> = (0..2)
            .map(|c| solution.kernel.entry(row, c).unwrap().clone())
            .collect();
        let generator_matrix = PolynomialMatrix::from_entries(2, 1, generator).unwrap();
        let annihilated = mul_matrix(&basis, &generator_matrix);
        assert!(annihilated.entry(0, 0).unwrap().is_zero());
    }
}

#[test]
fn wrong_length_targets_and_shifts_are_rejected() {
    let basis = matrix(
        1,
        2,
        alloc::vec![poly(&[b(1), b(1)]), poly(&[b(1), b(0), b(1)])],
    );
    let mut reduced = basis.clone();
    reduced.reduce_weak_popov(&[0, 0]).unwrap();
    assert!(
        reduced
            .membership_weak_popov(&[poly(&[b(1)])], &[0, 0])
            .is_err()
    );
    assert!(
        reduced
            .membership_weak_popov(&[poly(&[b(1)]), poly(&[b(1)]), poly(&[b(1)])], &[0, 0])
            .is_err()
    );
    assert!(
        basis
            .solve_weak_popov(&[poly(&[b(1)]), poly(&[b(1)])], &[0, 0])
            .is_err()
    );
    assert!(basis.rank_weak_popov(&[0]).is_err());
}

#[test]
fn identity_membership_and_solve_cover_zero_entries() {
    // Regression: the leading-term scan once returned `None` at the first
    // zero entry instead of skipping it, rejecting `[1, 0]` in `I_2`.
    let basis = matrix(
        2,
        2,
        alloc::vec![
            poly(&[b(1)]),
            Polynomial::zero(),
            Polynomial::zero(),
            poly(&[b(1)]),
        ],
    );
    let mut reduced = basis.clone();
    reduced.reduce_weak_popov(&[0, 0]).unwrap();
    let target = alloc::vec![poly(&[b(1)]), Polynomial::zero()];
    let witness = reduced.membership_weak_popov(&target, &[0, 0]).unwrap();
    assert_eq!(witness.quotients.len(), 2);
    let solution = basis.solve_weak_popov(&target, &[0, 0]).unwrap();
    assert_eq!(solution.particular, target);
}

#[test]
fn odd_characteristic_membership_uses_signed_cancellation() {
    use fgf::{Mersenne31, mersenne31};
    fn q(value: u32) -> <Mersenne31 as Field>::Elem {
        mersenne31::Elem::from_raw(value)
    }
    fn qpoly(coefficients: &[<Mersenne31 as Field>::Elem]) -> Polynomial<Mersenne31> {
        Polynomial::from_coefficients(coefficients).unwrap()
    }
    // Basis [[2+x, 0],[0, 1]] is reduced; target [(3+x)(2+x), 5] needs
    // the negative cancelling ratio (in characteristic two negation is
    // the identity, so only this fixture exercises the sign).
    let mut basis = PolynomialMatrix::from_entries(
        2,
        2,
        alloc::vec![
            qpoly(&[q(2), q(1)]),
            Polynomial::zero(),
            Polynomial::zero(),
            qpoly(&[q(1)]),
        ],
    )
    .unwrap();
    basis.reduce_weak_popov(&[0, 0]).unwrap();
    let factor = qpoly(&[q(3), q(1)]);
    let target = alloc::vec![
        factor.multiply(&qpoly(&[q(2), q(1)])).unwrap(),
        qpoly(&[q(5)]),
    ];
    let witness = basis.membership_weak_popov(&target, &[0, 0]).unwrap();
    let mut rebuilt = alloc::vec![Polynomial::zero(), Polynomial::zero()];
    for (row, quotient) in witness.quotients.iter().enumerate() {
        for (column, slot) in rebuilt.iter_mut().enumerate() {
            let term = basis
                .entry(row, column)
                .unwrap()
                .multiply(quotient)
                .unwrap();
            slot.add_assign(&term).unwrap();
        }
    }
    assert_eq!(rebuilt, target);
}

extern crate alloc;
